backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "index"
    label: "Home"
    folder: "src/pages"
    create: true
    filter: { field: data, value: true }
    slug: "home.{{fields.lang}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page" }
      - { label: "Id", name: "id", widget: "hidden", default: "home" }
      - { label: "Data", name: "data", widget: "hidden", default: "true" }
      - { label: "Language", name: "lang", widget: string }
      - {
          label: "Carrousel",
          name: "carrousel",
          widget: list,
          fields:
            [
              { label: "Background Image", name: image, widget: image },
              { label: "Title", name: "title", widget: "string", default: "test" },
              { label: "Subtitle", name: "subtitle", widget: text, default: "test" },
              { label: "button", name: "button", widget: "string", default: "test" },
            ],
        }
      - {
          label: About,
          name: about,
          widget: object,
          fields:
            [
              { label: Image, name: image, widget: image },
              { label: Title, name: title, widget: string, default: About Title },
              { label: Description, name: description, widget: text, default: Lorem ipsum dolor sit amet, consect etur adipiscing elit. },
              { label: Button, name: button, widget: string, default: button },
            ],
        }
      - {
          label: Products Section,
          name: productsSection,
          widget: object,
          fields:
            [
              { label: Section Title, name: sectionTitle, widget: string },
              {
                label: "Products",
                name: "products",
                widget: list,
                fields:
                  [
                    { label: "Background Image", name: image, widget: image },
                    { label: "Title", name: "title", widget: "string", default: "test" },
                    { label: "Subtitle", name: "subtitle", widget: text, default: "test" },
                  ],
              },
            ],
        }
      - {
          label: Certification Section,
          name: certificationsSection,
          widget: object,
          fields:
            [
              { label: Section Title, name: sectionTitle, widget: string },
              { label: Background Image, name: bgImage, widget: image },
              {
                label: Certifications,
                name: certifications,
                widget: list,
                fields:
                  [
                    { label: "Image", name: image, widget: image },
                    { label: "Title", name: "title", widget: "string", default: "test" },
                    { label: "Subtitle", name: "subtitle", widget: text, default: "test" },
                  ],
              },
            ],
        }
      - {
          label: Updates Section,
          name: updatesSection,
          widget: object,
          fields:
            [
              { label: Section Title, name: sectionTitle, widget: string },
              {
                label: Updates,
                name: updates,
                widget: list,
                fields:
                  [
                    { label: Image, name: image, widget: image },
                    { label: Title, name: title, widget: string, default: test },
                    { label: Date, name: date, widget: datetime, default: test },
                    { label: Button, name: button, widget: string, default: test },
                    { label: Subtitle, name: subtitle, widget: text, default: test },
                  ],
              },
            ],
        }

  - name: "updates"
    label: "Updates"
    folder: src/pages/updates
    create: true
    filter: { field: data, value: true }
    slug: updates.{{fields.lang}}
    fields:
      - { label: Template Key, name: templateKey, widget: hidden, default: updates-page }
      - { label: Id, name: id, widget: hidden, default: updates }
      - { label: Data, name: data, widget: hidden, default: true }
      - { label: Language, name: lang, widget: string }
      - {
          label: Carrousel,
          name: carruselSection,
          widget: object,
          fields:
            [
              { label: title, name: title, widget: string, default: test },
              { label: subtitle, name: subtitle, widget: string, default: test },
              { label: Carrousel Images, name: images, widget: list, fields: [{ label: Image, name: image, widget: image }] },
            ],
        }
      - {
          label: Updates Section,
          name: updatesSection,
          widget: object,
          fields:
            [
              { label: Data, name: data, widget: text },
              { label: Title, name: sectionTitle, widget: string, default: Noticias },
              {
                label: Updates,
                name: updates,
                widget: list,
                fields:
                  [
                    { label: Image, name: image, widget: image },
                    { label: Title, name: title, widget: string, default: Noticia 1 },
                    { label: Date, name: date, widget: datetime },
                    { label: Button, name: button, widget: string, default: Button },
                    {
                      label: Subtitle,
                      name: subtitle,
                      widget: string,
                      default: Lorem ipsum dolor sit amet,
                      consectetur adipiscing elit,
                      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.,
                    },
                  ],
              },
            ],
        }
  - name: "updates"
    label: "Updates"
    folder: src/pages/updates
    create: true
    filter: { field: data, value: true }
    slug: updates.{{fields.lang}}
    fields:
      - {
          label: Section 1,
          name: section1,
          widget: object,
          fields: [{ label: title, name: title, widget: string, default: test }, { label: subtitle, name: subtitle, widget: string, default: test }],
        }
      - {
          label: Section 2,
          name: section2,
          widget: object,
          fields:
            [
              {
                label: Cards,
                name: cards,
                widget: list,
                fields:
                  [{ label: title, name: title, widget: string, default: test }, { label: subtitle, name: subtitle, widget: string, default: test }],
              },
            ],
        }

  # - name: blog
  #   label: Blog
  #   folder: src/pages/blog
  #   create: true
  #   slug: {{year}}-{{month}}-{{day}}-{{slug}}
  #   fields:
  #     - {label: Template Key, name: templateKey, widget: hidden, default: blog-post}
  #     - {label: Title, name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Description", name: "description", widget: "text"}
  #     - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
  #     - {label: "Featured Image", name: "featuredimage", widget: image}
  #     - {label: "Body", name: "body", widget: "markdown"}
  #     - {label: "Tags", name: "tags", widget: "list"}

  # - name: "pages"
  #   label: "Pages"
  #   files:
  #     - file: "src/pages/index.md"
  #       label: "Landing Page"
  #       name: "index"
  #       fields:
  #         - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
  #         - {label: Title, name: title, widget: string}
  #         - {label: Image, name: image, widget: image}
  #         - {label: Heading, name: heading, widget: string}
  #         - {label: Subheading, name: subheading, widget: string}
  #         - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
  #         - {label: Description, name: description, widget: string}
  #         - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
  #         - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
  #     - file: "src/pages/about/index.md"
  #       label: "About"
  #       name: "about"
  #       fields:
  #         - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
  #         - {label: "Title", name: "title", widget: "string"}
  #         - {label: "Body", name: "body", widget: "markdown"}
  #     - file: "src/pages/products/index.md"
  #       label: "Products Page"
  #       name: "products"
  #       fields:
  #         - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
  #         - {label: Title, name: title, widget: string}
  #         - {label: Image, name: image, widget: image}
  #         - {label: Heading, name: heading, widget: string}
  #         - {label: Description, name: description, widget: string}
  #         - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
  #         - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
  #         - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
  #         - {label: Full_image, name: full_image, widget: image}
  #         - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
